$(document).ready(function(){
    $(".openMenu").click(function(){
        $(".navOver").slideToggle(400);
        $(".wrapper").css("position","fixed");
    });
});
$(document).ready(function(){
    $(".close").click(function(){
        $(".navOver").slideToggle(400);
        $(".wrapper").css("position","");
    });
});